export const products = [
    {
        _id: 1,
        title: 'Alice Adventures in Wonderland',
        author: 'Lewis Carol',
        image: '/images/lewis-carrol-alices-adventures-in-wonderland.webp',
        category: 'adventures',
        language: 'english',
        price: 18.99,
        countInStock: 3,
        onSale: false,
        rating: 4,
        numReviews: 10,
        ageRange: 'middle-grade',
    },
    {
        _id: 2,
        title: 'Paddington at the zoo',
        author: 'Michael Bond',
        image: '/images/michael-bond-paddington-at-the-zoo.webp',
        category: 'classic',
        language: 'english',
        price: 12.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'early-reader',
    },
    {
        _id: 3,
        title: 'Through the looking glass',
        author: 'Lewis Carol',
        image: '/images/lewis-carrol-through-the-looking-glass.webp',
        category: 'adventures',
        language: 'english',
        price: 16.99,
        availability: 'comming-soon',
        onSale: false,
        rating: 4,
        ageRange: 'middle-grade',
    },
    {
        _id: 4,
        title: 'Charles Darwin',
        author: 'Maria Vegara',
        image: '/images/little-people-big-dreams-charles-darwin.webp',
        category: 'biographies',
        language: 'english',
        price: 13.99,
        availability: 'in-stock',
        onSale: true,
        rating: 4,
        ageRange: 'middle-grade',
    },
    {
        _id: 5,
        title: 'Paddington at the Palace',
        author: 'Michael Bond',
        image: '/images/michael-bond-paddington.webp',
        category: 'classic',
        language: 'english',
        price: 9.99,
        availability: 'in-stock',
        onSale: false,
        rating: 4,
        ageRange: 'early-reader',
    },
    {
        _id: 6,
        title: 'Matilda',
        author: 'Roald Dahl',
        image: '/images/roald-dahl-matilda.webp',
        category: 'classic',
        language: 'english',
        price: 11.99,
        availability: 'in-stock',
        onSale: false,
        rating: 1,
        ageRange: 'early-reader',
    },
    {
        _id: 7,
        title: 'Valse mélancolique. Вибрані твори',
        author: 'Ольга Кобилянська',
        image: '/images/olha-kobylianska-valse-melancolique.jpg',
        category: 'classic',
        language: 'ukrainian',
        price: 11.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 8,
        title: 'Я (Романтика)',
        author: 'Микола Хвильовий',
        image: '/images/mykola-hvyliovyi-ya-romantyka.jpg',
        category: 'classic',
        language: 'ukrainian',
        price: 11.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 9,
        title: 'Місто',
        author: 'Валерʼян Підмогильний',
        image: '/images/valerian-pidmohylnyi-misto.jpg',
        category: 'classic',
        language: 'ukrainian',
        price: 11.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 10,
        title: 'Танець недоумка',
        author: 'Ілларіон Павлюк',
        image: '/images/illarion-pavliuk-tanec-nedoumka.jpg',
        category: 'sci-fi',
        language: 'ukrainian',
        price: 14.99,
        availability: 'in-stock',
        onSale: false,
        rating: 6,
        ageRange: 'adult',
    },
    {
        _id: 11,
        title: 'Дім Солі',
        author: 'Світлана Тараторіна',
        image: '/images/svitlana-taratorina-dim-soli.jpg',
        category: 'sci-fi',
        language: 'ukrainian',
        price: 13.99,
        availability: 'in-stock',
        onSale: true,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 12,
        title: 'Shadow and Bone',
        author: 'Leigh Bardugo',
        image: '/images/leigh-bardugo-shadow-and-bone.jpg',
        category: 'fantasy',
        language: 'dutch',
        price: 16.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'young-adult',
    },
    {
        _id: 13,
        title: 'Kraai & Koninkrijk',
        author: 'Leigh Bardugo',
        image: '/images/leigh-bardugo-kraai-en-koninkrijk.jpg',
        category: 'fantasy',
        language: 'dutch',
        price: 14.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'young-adult',
    },
    {
        _id: 14,
        title: 'Im Westen nichts Neues',
        author: 'Erich Maria Remarque',
        image: '/images/remarque-im-westen-nichts-neues.jpg',
        category: 'classic',
        language: 'german',
        price: 11.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 15,
        title: 'Narziß und Goldmund',
        author: 'Hermann Hesse',
        image: '/images/hermann-hesse-narziss-und-goldmund.jpg',
        category: 'classic',
        language: 'german',
        price: 9.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
    {
        _id: 16,
        title: 'Sherlock Holmes: The Complete Novels and Stories, Volume I',
        author: 'Arthur Conan Doyle',
        image: '/images/sherlock-holmes-the-complete-novels-and-stories.jpg',
        category: 'detective',
        language: 'english',
        price: 19.99,
        availability: 'in-stock',
        onSale: true,
        rating: 6,
        ageRange: 'adult',
    },
    {
        _id: 17,
        title: 'Friends, Lovers, and the Big Terrible Thing',
        author: 'Matthew Perry',
        image: '/images/matthew-perry-friends-lovers-and-the-big-terrible-thing.jpg',
        category: 'biographies',
        language: 'english',
        price: 19.99,
        availability: 'in-stock',
        onSale: false,
        rating: 5,
        ageRange: 'adult',
    },
];
